// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWE8kQB0ze1mUvlWVpnlpyeQlQfvnnTdE',
    appId: '1:929378051122:web:fa305bbe09e65dbf6e482b',
    messagingSenderId: '929378051122',
    projectId: 'mini-chat-1fef6',
    authDomain: 'mini-chat-1fef6.firebaseapp.com',
    storageBucket: 'mini-chat-1fef6.firebasestorage.app',
    measurementId: 'G-X2T0H8M3GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOYrkBxVxGtsS3mkNrt7QMdA4PR2sEmXM',
    appId: '1:929378051122:android:4a7b4f0eb5f4b4006e482b',
    messagingSenderId: '929378051122',
    projectId: 'mini-chat-1fef6',
    storageBucket: 'mini-chat-1fef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgeSRYnLhEPvqDLIMXAE0o51cz2sjsLcg',
    appId: '1:929378051122:ios:0771bf62b9510bb46e482b',
    messagingSenderId: '929378051122',
    projectId: 'mini-chat-1fef6',
    storageBucket: 'mini-chat-1fef6.firebasestorage.app',
    iosBundleId: 'com.example.miniChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgeSRYnLhEPvqDLIMXAE0o51cz2sjsLcg',
    appId: '1:929378051122:ios:0771bf62b9510bb46e482b',
    messagingSenderId: '929378051122',
    projectId: 'mini-chat-1fef6',
    storageBucket: 'mini-chat-1fef6.firebasestorage.app',
    iosBundleId: 'com.example.miniChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWE8kQB0ze1mUvlWVpnlpyeQlQfvnnTdE',
    appId: '1:929378051122:web:a2a3eca3683504556e482b',
    messagingSenderId: '929378051122',
    projectId: 'mini-chat-1fef6',
    authDomain: 'mini-chat-1fef6.firebaseapp.com',
    storageBucket: 'mini-chat-1fef6.firebasestorage.app',
    measurementId: 'G-VM052413LN',
  );
}
